[[manager.prepend_keymap]]
on   = [ "c", "p" ]
run  = "copy path"
desc = "Copiar ruta absoluta"

[[manager.prepend_keymap]]
on   = [ "c", "f" ]
run  = "copy filename"
desc = "Copiar nombre del archivo"

# Saltar directamente a configuraciones
[[manager.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "Ir a ~/.config"

[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Ir a ~/Downloads"
